version: "3.8"

services:
  web:
    build:
      context: app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql
    env_file:
      - .env.dev
