# Generated by Django 4.1.3 on 2022-11-24 14:02

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        BtreeGistExtension(),
    ]
